version: '3.4'

services:
  simplefolio:
    image: simplefolio
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 1234:1234
